# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-04 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', filebrowser.fields.FileBrowseField(max_length=500)),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Actief')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('date_finished', models.DateField(verbose_name='Date finished')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'ordering': ['-date_finished'],
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
    ]
